fix(fido2): tests are failing due to NoClassDefFoundError: javax/xml/bind/annotation/XmlElement #6865 (#6866)
Signed-off-by: YuriyZ <yzabrovarniy@gmail.com>