fix(fido2): tests are failing due to NoClassDefFoundError: javax/xml/bind/annotation/XmlElement #6865 (#6866)
Signed-off-by: YuriyZ <yzabrovarniy@gmail.com>
Former-commit-id: 513a7606af2e72221768d676937fe43c5a77d2ae