UIComponentBase failed to validate 'loginForm:username' thus renamed 'loginForm_username'
java.lang.IllegalArgumentException: loginForm:username
        at javax.faces.component.UIComponentBase.validateId(UIComponentBase.java:593) ~[javax.faces-2.2.16.jar:2.2.16]

https://github.com/GluuFederation/oxAuth/issues/1296